#ifndef  DELETE_CHARACTER_CODES_H
#define  DELETE_CHARACTER_CODES_H

#define	CHARACTER_DOESNT_EXIST		0x01
#define	CHARACTER_DELETE_FAILED		0x02
#define	CHARACTER_DELETE_SUCCESS	0x03

#endif // ! DELETE_CHARACTER_CODES_H
